### ISSUE TITLE
/sferes/misc/rand.hpp:79 : Assertion `max > min' failed.

### ISSUE THREAD

**Issue by AranBSmith** [sferes2/sferes2#101]
I often get the below assertion error when trying to run an ea (Map Elites module). 

This happens very shortly after initiating the ea only, so if it does not happen then, the rest of the ea will run totally fine. Is this an issue with generating individuals? Im not too sure.. 
Current work around is to keep running the ea and hope this doesn't happen.

```
sferes2 version: ca0781ab324b8444bd7779a41b20169f142c7ca2 
seed: 1564465505 
rhex_text: ../sferes/misc/rand.hpp:79: T sferes::misc::rand(T, T, std::true_type) [with T = int; std::true_type = std::integral_constant<bool, true>]: Assertion `max > min' failed.
```

**Comment by JoostHuizinga** [comment]
Is it possible for you to obtain the full stack trace so we can see where rand is called?

**Comment by AranBSmith** [comment]
Using gdb

```
aran@aran-HP-ENVY-x360-Convertible-13-ag0xxx:~/itev2/sferes2$ gdb --args ./build/exp/MAP-Elites-Rhex/rhex_text
GNU gdb (Ubuntu 8.2-0ubuntu1~16.04.1) 8.2
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./build/exp/MAP-Elites-Rhex/rhex_text...(no debugging symbols found)...done.
(gdb) run
Starting program: /home/aran/itev2/sferes2/build/exp/MAP-Elites-Rhex/rhex_text 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Version: 2307.1
sferes2 version: ca0781ab324b8444bd7779a41b20169f142c7ca2
seed: 1564514718
[New Thread 0x7ffff0889700 (LWP 17458)]
[New Thread 0x7fffe8488700 (LWP 17459)]
[New Thread 0x7ffff0488700 (LWP 17460)]
[New Thread 0x7fffebfff700 (LWP 17461)]
[New Thread 0x7fffebbfe700 (LWP 17462)]
[New Thread 0x7fffeb7fd700 (LWP 17463)]
[New Thread 0x7fffeb3fc700 (LWP 17464)]
rhex_text: ../sferes/misc/rand.hpp:79: T sferes::misc::rand(T, T, std::true_type) [with T = int; std::true_type = std::integral_constant<bool, true>]: Assertion `max > min' failed.

Thread 1 "rhex_text" received signal SIGABRT, Aborted.
0x00007ffff50bd428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff50bd428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff50bf02a in __GI_abort () at abort.c:89
#2  0x00007ffff50b5bd7 in __assert_fail_base (fmt=<optimised out>, 
    assertion=assertion@entry=0x449276 "max > min", 
    file=file@entry=0x44925e "../sferes/misc/rand.hpp", line=line@entry=79, 
    function=function@entry=0x44f340 <sferes::misc::rand<int>(int, int, std::integral_constant<bool, true>)::__PRETTY_FUNCTION__> "T sferes::misc::rand(T, T, std::true_type) [with T = int; std::true_type = std::integral_constant<bool, true>]") at assert.c:92
#3  0x00007ffff50b5c82 in __GI___assert_fail (assertion=0x449276 "max > min", 
    file=0x44925e "../sferes/misc/rand.hpp", line=79, 
    function=0x44f340 <sferes::misc::rand<int>(int, int, std::integral_constant<bool, true>)::__PRETTY_FUNCTION__> "T sferes::misc::rand(T, T, std::true_type) [with T = int; std::true_type = std::integral_constant<bool, true>]") at assert.c:101
#4  0x0000000000432cb7 in sferes::ea::MapElites<sferes::phen::Parameters<sferes::gen::Sampled<23, Params, stc::Itself>, FitAdapt<Params, stc::Itself>, Params, stc::Itself>, sferes::eval::Parallel<Params, stc::Itself>, boost::fusion::vector<sferes::stat::Map<sferes::phen::Parameters<sferes::gen::Sampled<23, Params, stc::Itself>, FitAdapt<Params, stc::Itself>, Params, stc::Itself>, Params, stc::Itself>, sferes::stat::MapProgress<sferes::phen::Parameters<sferes::gen::Sampled<23, Params, stc::Itself>, FitAdapt<Params, stc::Itself>, Params, stc::Itself>, Params, stc::Itself>, boost::fusion::void_, boost::fusion::void_, boost::fusion::void_, boost::fusion::void_, boost::fusion::void_, boost::fusion::void_, boost::fusion::void_, boost::fusion::void_>, sferes::modif::Dummy<stc::_Params, stc::Itself>, Params, stc::Itself>::epoch() ()
#5  0x000000000043dd28 in sferes::ea::Ea<sferes::phen::Parameters<sferes::gen::Sampled<23, Params, stc::Itself>, FitAdapt<Params, stc::Itself>, Params, stc::Itself>, sferes::eval::Parallel<Params, stc::Itself>, boost::fusion::vector<sferes::stat::Map<sferes::phen::Parameters<sferes::gen::Sampled<23, Params, stc::Itself>, FitAdapt<Params, stc::Itself>, Params, stc::Itself>, Params, stc::Itself>, sferes::stat::MapProgress<sferes::phen::Parameters<sferes::gen::Sampled<23, Params, stc::Itself>, FitAdapt<Params, stc::Itself>, Params, stc::Itself>, Params, stc::Itself>, boost::fusion::void_, boost::fusion::void_, boost::fusion::void_, boost::fusion::void_, boost::fusion::void_, boost::fusion::void_, boost::fusion::void_, boost::fusion::void_>, sferes::modif::Dummy<stc::_Params, stc::Itself>, Params, sferes::ea::MapElites<sferes::phen::Parameters<sferes::gen::Sampled<23, Params, stc::Itself>, FitAdapt<Params, stc::Itself>, Params, stc::Itself>, sferes::eval::Parallel<Params, stc::Itself>, boost::fusion::vector<sferes::stat::Map<sferes::phen::Parameters<sferes::gen::Sampled<23, Params, stc::Itself>, FitAdapt<Params, stc::Itself>, Params, stc::Itself>, Params, stc::Itself>, sferes::stat::MapProgress<sferes::phen::Parameters<sferes::gen::Sampled<23, Params, stc::Itself>, FitAdapt<Params, stc::Itself>, Params, stc::Itself>, Params, stc::Itself>, boost::fusion::void_, boost::fusion::void_, boost::fusion::void_, boost::fusion::void_, boost::fusion::void_, boost::fusion::void_, boost::fusion::void_, boost::fusion::void_>, sferes::modif::Dummy<stc::_Params, stc::Itself>, Params, stc::Itself> >::run(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#6  0x000000000041b2b2 in main ()
(gdb) 

```

**Comment by AranBSmith** [comment]
I highly suspect this to be caused by constraints in the simulation that causes all individuals to be discarded.. does this seem right here?

**Comment by Aneoshun** [comment]
Hi @AranBSmith, 
Yes, your hypothesis could be the cause of this issue. Can you change some of your constraints to check this?

**Comment by AranBSmith** [comment]
Yes, I did have a bad constraint which eliminated the majority of individuals, after easing the constraint this assertion does not fail.

**Comment by Aneoshun** [comment]
Glad to hear this. We might want to check this earlier in the code and print a userfriendly message to avoid people to face the same problem
